let data=[];
const grid=document.getElementById('grid');const filters=document.getElementById('filters');const count=document.getElementById('count');const detail=document.getElementById('detail');const detailInner=document.getElementById('detailInner');
const categories=['All','Outdoor Seating','Outdoor Lounge','Outdoor Dining','Outdoor Bar','Outdoor Sun Loungers','Outdoor Tables','Accessories'];
let active='All';
function catsFor(x){const c=x.category.toLowerCase();const out=[];if(c.includes('seating'))out.push('Outdoor Seating');if(c.includes('lounge'))out.push('Outdoor Lounge');if(c.includes('dining'))out.push('Outdoor Dining');if(c.includes('bar'))out.push('Outdoor Bar');if(c.includes('sun loungers'))out.push('Outdoor Sun Loungers');if(c.includes('tables'))out.push('Outdoor Tables');if(c.includes('accessories'))out.push('Accessories');return out}
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="filter ${c===active?'active':''}" data-c="${c}">${c}</button>`).join('');filters.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{active=b.dataset.c;renderFilters();renderGrid();});}
function renderGrid(){const list=active==='All'?data:data.filter(x=>catsFor(x).includes(active));count.textContent=`${list.length} collections`;grid.innerHTML=list.map(x=>`<article class="card" data-id="${x.id}"><div class="card-image"><img loading="lazy" src="${x.images[0]}" alt="${x.name}"></div><div class="card-body"><div><div class="card-title">${x.name}</div><div class="card-cat">${x.category}</div></div><div class="card-arrow">↗</div><div class="card-tag">${x.tagline}</div></div></article>`).join('');grid.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));}
function openDetail(id){const x=data.find(a=>a.id===id);if(!x)return;detail.style.display='block';detailInner.innerHTML=`<div class="detail-wrap"><div class="detail-head"><div><div class="eyebrow">TRY IT INDIA • ${x.category}</div><h2>${x.name}</h2><div class="eyebrow">${x.tagline}</div></div><button class="close" onclick="closeDetail()">Close ×</button></div><div class="sheet-grid">${x.images.map((im,i)=>`<img src="${im}" alt="${x.name} catalogue sheet ${i+1}">`).join('')}</div><div class="items"><h3>Catalogue elements</h3><div class="item-grid">${x.products.map((p,i)=>`<div class="item"><span>${String(i+1).padStart(2,'0')}</span>${p}</div>`).join('')}</div></div><div style="margin-top:28px"><a class="button" href="https://wa.me/919582053344?text=${encodeURIComponent('Hello TRY IT INDIA, I want details for '+x.name)}" target="_blank" rel="noopener">Enquire for ${x.name}</a></div></div>`;detail.scrollIntoView({behavior:'smooth',block:'start'});}
function closeDetail(){detail.style.display='none';detailInner.innerHTML='';}
window.closeDetail=closeDetail;
fetch('catalog.json').then(r=>r.json()).then(d=>{data=d;renderFilters();renderGrid();}).catch(err=>{grid.innerHTML='<p style="padding:30px;color:#a00">Catalogue data could not load. Make sure catalog.json is uploaded beside index.html.</p>';console.error(err);});
