document.addEventListener('DOMContentLoaded',()=>{
 const nav=document.querySelector('.nav'),hamb=document.querySelector('.hamb'); hamb?.addEventListener('click',()=>{nav.classList.toggle('open');hamb.textContent=nav.classList.contains('open')?'×':'☰'});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
 const grid=document.getElementById('productGrid'), search=document.getElementById('searchInput'), sort=document.getElementById('sortSelect'); let filter='all';
 const wa=n=>`https://wa.me/919582053344?text=${encodeURIComponent('Hello TRY IT INDIA, I want details for '+n+'.')}`;
 function render(){let list=PRODUCTS.filter(p=>(filter==='all'||p.category===filter||p.material===filter||filter==='Accessory'&&p.tag==='Accessory')&&(!search.value||p.name.toLowerCase().includes(search.value.toLowerCase())));if(sort.value==='az')list.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=list.map((p,i)=>`<article class="product" data-i="${PRODUCTS.indexOf(p)}"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span>${p.tag}</span><button class="quick" aria-label="Quick view">＋</button></div><div class="product-copy"><small>${p.material} • ${p.category}</small><h3>${p.name}</h3><a href="${wa(p.name)}" target="_blank">Enquire Now <b>→</b></a></div></article>`).join('');grid.querySelectorAll('.product').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('a'))return;openModal(Number(c.dataset.i))}));}
 function setFilter(f){filter=f;document.querySelectorAll('#chips button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));render();document.getElementById('products').scrollIntoView({behavior:'smooth'})}
 document.querySelectorAll('#chips button').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));document.querySelectorAll('.material-grid button').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));sort.addEventListener('change',render);search.addEventListener('input',render);
 const catGrid=document.getElementById('categoryGrid');catGrid.innerHTML=CATEGORIES.map(c=>`<button class="category-card" data-cat="${c[2]}"><img src="${c[1]}" alt="${c[0]}"><span>${c[0]} <b>→</b></span></button>`).join('');catGrid.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.cat)));
 const modal=document.getElementById('productModal'),mi=document.getElementById('modalImage'),mt=document.getElementById('modalTitle'),md=document.getElementById('modalDesc'),mw=document.getElementById('modalWA');
 function openModal(i){const p=PRODUCTS[i];mi.src=p.image;mi.alt=p.name;mt.textContent=p.name;md.textContent='Premium outdoor furniture from TRY IT INDIA. Enquire for dimensions, finishes, colour options, availability and project requirements.';mw.href=wa(p.name);modal.classList.add('show');document.body.classList.add('locked')}
 document.querySelector('[data-close]')?.addEventListener('click',()=>{modal.classList.remove('show');document.body.classList.remove('locked')});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('show');document.body.classList.remove('locked')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('show');document.body.classList.remove('locked')}});
 render();
});
